### PR TITLE
Upgrade to support atuin 16

### PR DESCRIPTION
**Pull request by gmemstr**
Still a work in progress, some functions currently stubbed.

### CODE REVIEW

**Comment by gmemstr** [comment]
@conradludgate I'm currently testing this locally, but from what I can tell it's now working so marking as ready for review. Is there any want to eventually merge this into upstream?

**Review by conradludgate — APPROVED** [review]
Looks good. Thanks

**Comment by gmemstr** [comment]
@conradludgate Sorry, to clarify, I meant Atuin upstream not this repo ;p Realized that might've come off a bit passive aggressive. I dug up some of the threads on this topic in the main repo so keeping an eye on those now. Thanks!

**Comment by conradludgate** [comment]
Yeah, best to keep that discussion to the forum thread that I see you found. We're still considering it

**Pull request merged**
